server:
  port: 8080
  jackson:
    serialization:
      write-dates-as-timestamps: true

spring:
  application:
    name: jsoup-demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/jsoup?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: zhouchao

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.raydata.prize.domain
  configLocation: classpath:mybatis-config.xml


keyword:
  search:
    size: 10
    list:
    - 百吉福（MILKANA）棒棒奶酪 原味 500g/25粒装 哆啦A梦版儿童奶酪棒 高钙健康休闲零食
    - colorkey珂拉琪小黑镜唇釉唇彩唇蜜口红滋润保湿持久显色女学生唇釉礼物 P707 浆果摩卡
    - 闪迪(SanDisk)256GB USB3.0 U盘 CZ410酷邃 商务办公优选
    - colorkey珂拉琪丝绒空气哑光唇釉唇泥不易掉色防水番茄蜜桃唇彩唇蜜口红女学生礼物 R888 招财红梨
    - 好奇Huggies皇家御裤纸尿裤M96片(6-11kg)中号婴儿尿不湿御级丝柔龙纹裤皇家铂金新老包装随机发货
    - Apple iPhone 12 mini (A2400) 64GB 红色 手机 支持移动联通电信5G
    - 力士(LUX)精油香氛沐浴露 幽莲1kg+桃花1kg送幽莲350g+桃花100gx2迪丽热巴同款持续留香（新老包装随机发货）
    - Apple AirPods Pro 主动降噪无线蓝牙耳机 适用iPhone/iPad/Apple Watch
    - 广州酒家利口福 虾饺 160g  8个 冷冻保存 早餐 火锅食材 饺子 早茶点心 方便菜
    - 桂格 奇亚籽混合燕麦片420克 五谷伴侣好营养 进口原料 健身运动之选
    - 【新用户专享可叠加滴滴价】滴滴加油优惠券满200减30元200减20元200减10元各1张 面值60
    - 妙洁保鲜袋组合装特大号40只大号80中号120共240只 加厚实塑料保险食品袋子厨房超市
    - 必品阁（bibigo）韩式泡菜王饺子840g 24只装 水饺 蒸饺 煎饺 锅贴 早餐食材
    - 方家铺子 鸡头米 芡实 炖汤煲粥配料红皮芡实500g 始于1906
    - 黑人（DARLIE）双重薄荷牙膏225g 清新口气 防蛀固齿（新旧包装随机发放）
    - 妙洁 厚质铝箔烘焙纸15米盒装 锡纸 不易焦黑易撕断 烘焙烧烤烤箱可用
    - 黑人（DARLIE）超白密泡小苏打牙膏140g 去牙渍（新老包装随机发放）
    - 每日鲜语 鲜牛奶 1L 高品质原生高钙 巴氏杀菌鲜奶
    - 袋鼠医生儿童口罩独立包装3d立体婴儿1岁2岁3岁宝宝婴幼儿一次性防护口罩 30支S码女宝
    - 好奇Huggies铂金装纸尿裤NB84片(5kg以下)新生儿小号婴儿尿不湿裸感超薄透气 新老包装随机发货
    - 大王GOON 花信风纸尿裤 NB90片(5kg以下)新生儿宝宝超薄透气
    - "[买1送1]UNNY官方旗舰店防晒霜乳美白防紫外线清爽隔离三合一正品"
    - kissport_无糖薄荷糖网红香体接吻清新口气口香糖果便携流口水A
    - 摇滚动物园野草莓身体磨砂膏果酸去角质焕亮女全身改善疙瘩毛囊
    - 2021新款防晒衣男女超薄款透气冰丝外套轻薄衫钓鱼服防紫外线夏季
    - 三月兔marchare朝雾玫瑰美妆蛋不吃粉化妆蛋干湿两用彩妆蛋
    - 防晒衣女2021新款冰丝防晒服外套夏季薄款紫外线透气防晒罩衫开衫
    - 豆腐猫砂除臭无尘豆腐砂渣猫咪用品混合猫沙大袋满10公斤20斤包邮
    - Petshy6L天然豆腐猫砂细混合型10膨润土除臭无尘大袋2.5公斤包邮
    - 坚果混合零食大礼包炒货组合装碧根果巴旦木核桃等女生零食任选
    - polo衫定制t恤文化广告工作衣服装定做聚会班服短袖diy印字图logo
    - 植护棉柔巾婴儿用擦脸巾干湿两用抽取式洁面便携装一次性洗脸巾女
    - 【雪梨推荐】完美日记小细跟口红INTO1-刘宇同款唇膏唇釉唇彩
    - 50袋】肌肉小王子速食鸡胸肉健身代餐即食低脂卡零食鸡肉轻食食品
    - kilala可啦啦玻尿酸美瞳日抛女10片隐形眼镜正品大牌非半年抛月抛
    - 蜗牛移动 官方直充50元手机话费充值免卡充值
    - "【薇娅推荐】超值汰渍全效洗衣液家庭装去渍清香持久留香3kg*2瓶"
    - "Lay’s/乐事薯片超值分享装70g*3包（原味/红烩/烧烤）零食小吃"
    - 良品铺子肉松海苔吐司肉松面包整箱面包早餐食品营养健康零食小吃
    - 汰渍洗衣皂360度柠檬清香无磷去污渍净白126g*4块
    - 威猛先生清香480g*3瓶家用洁厕液
    - 珀莱雅羽感抗蓝光防紫外线防晒霜
    - 康巴赫官方旗舰不锈钢蜂窝不粘锅
    - 护舒宝液体always量多日用女卫生巾
    - 闪魔钢化mate30荣耀10 nova5pro版膜
    - 卫龙大面筋麻辣儿时礼包小零食辣条
    - 【卫龙_魔芋爽】魔芋素毛肚解馋辣条
    - 认养一头牛常温原味儿童200g早餐奶
    - "[2支68元]unny官方旗舰店眼线胶"
    - 维达实惠装家用厕所纸巾实心批厕纸
    - 清风整箱大包实惠装家用卫生纸
    - 干裙带菜特级旗舰店韩式韩国0裙菜
    - 好欢螺螺蛳粉柳州特产螺狮粉方便面
    - "闪魔苹果11 / x防窥膜xr xs防偷窥膜"
    - "【新色】judydoll橘朵单色腮红奶茶"
    - 丽芙甲硝唑凝胶消炎甲硝锉软膏正品
    - 极地火户外大沿遮阳帽男女防晒沙滩帽徒步登山骑电动车折叠渔夫帽
    - 四季通用,钓鱼底窝鲫鱼鲤鱼,打窝米通杀野钓鱼食
    - KACO优写4色中性笔多功能四色水笔多色合一0.5黑蓝红绿4色合1水笔
    - 钓箱背带达瓦钓箱2900 3000 3500 2700通用背带加厚垫肩现货
    - 多功能雷极钓箱超硬四角升降黑坑野钓32升全套配件高坐姿钓鱼箱
    - 懒人记账本可爱家庭理财笔记本文具简约多功能财务明细收支
    - 现金日记账本收入支出明细账财务记账本店铺经营现金流水台账本
    - 日本UNI三菱按动水笔芯UMR-83/85N K6中性笔芯适用于UMN-155盒装
    - 法汀妮芦荟胶保湿补水滋润细致毛孔晒后修护免洗面膜凝胶护肤正品
    - 白色珠光膜气泡袋快递打包气泡信封袋气泡膜袋防震包装袋子
    - 水彩笔套装画笔蜡笔绘画套装儿童小学生画画全套200pc
    - 白云自在 0.9 羊毫加健兼毫毛笔 文益笔庄经典毛笔
    - 氨基酸洗面奶女深层清洁美白补水洗面奶男士去黑头祛痘洁面乳慕斯
    - 折叠美工刀 多功能电工刀重型裁纸壁纸刀地毯割刀开箱刀梯形刀片
    - 纸箱刀壁纸刀介刀五金工具刀片物流美工刀快递刀拆箱刀电商美工刀【7月2日发完】
    - SOFEI氨基酸洗面奶学生控油祛痘深层清洁去黑头温和洁面卸妆套盒
    - 去痘印去痘痘粉刺祛痘印坑修复膏霜祛痘神器青春祛痘除螨洗面奶
    - 卓越佳印加厚75克85克A4A3复印纸打印纸草稿白纸 单包装/500张
    - 中药小颗粒海藻面膜美白补水祛黄控油祛痘紧致提亮清洁收缩毛孔
