server:
  port: 8880

logging:
  level:
    root: info
    org.mybatis: debug
    java.sql: debug
    org.springframework.web: trace

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: scheduler.domain
  configLocation: classpath:mybaties-config.xml

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-test
    username: root
    password: zhc4664