server:
  port: 8880

logging:
  level:
    root: info
    org.mybatis: debug
    java.sql: debug
    org.springframework.web: trace

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.raydata.model
  configLocation: classpath:mybaties-config.xml