server:
  port: 8881

spring:
  application:
    name: security-app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/test?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: zhouchao

jwt:
  header: Authorization
  path: /login