server:
  port: 8881

spring:
  application:
    name: security-app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/test?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: zhouchao

jwt:
  login: /**/user/login
  logout: /**/user/logout

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.raydata.prize.domain
  configLocation: classpath:mybaties-config.xml