server:
  port: 8180

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/elasticsearch?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: zhouchao
  elasticsearch:
    rest:
      uris: "192.168.233.103:9200"

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:mybaties-config.xml

index:
  example: example_index
  template-sign: template_sign_index