server:
  port: 8765

logging:
  level:
    root: info
    org.mybatis: debug
    java.sql: debug
    org.springframework.web: trace

spring:
  redis:
    timeout: 2000
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 24
        max-wait: 1000


